### ISSUE TITLE
Process job description posted by dpsim API

### ISSUE THREAD

**Issue by m-mirz** [sogno-platform/dpsim-worker#2]
The docker image could look similar to this one: https://github.com/sogno-platform/dpsim/blob/master/Packaging/Docker/Dockerfile
As base, sogno/dpsim:dev should be used. rwthacs is deprecated.

The python code could be similar to this one: https://github.com/sogno-platform/dpsim/blob/master/Examples/Notebooks/Grids/CIGRE_MV_powerflow-dpsimpy.ipynb

It reads the topology from CGMES XML files and creates a CSV file with results, which can be uploaded somewhere.

**Comment by richardmarston** [comment]
Closed by pull request https://github.com/sogno-platform/dpsim-worker/pull/3
